### ISSUE TITLE
armhf and armel builds

### ISSUE THREAD

**Issue by y8** [OctoPrint/docker#6]
Hello!

It would be nice to have automatic builds for armhf arch as well. 

SEE: https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

Cheers!

**Comment by cmgrass** [comment]
Not sure if this is related, but:

pi@mypi:~/octoprint-docker $ docker-compose up -d
Starting octoprint
pi@mypi:~/octoprint-docker $ docker-compose logs -f
Attaching to octoprint
octoprint    | standard_init_linux.go:190: exec user process caused "exec format error"
octoprint exited with code 1

I assume this is because the raspberry pi is ARM

I will try to build a container

**Comment by williamwebb** [comment]
To this point, this should be turned into a [multi-arthicture image](https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/)

**Comment by yamlCase** [comment]
inspecting the Dockerfile, the parent image `FROM python:2.7` does support multi architecture including arm.  My guess is the main code README.md will work for docker-compose as it is building the image prior to run.  

For the "without docker-compose" documentation, you'll need to build it first: `docker build -t octoprint:pi` then in the run command replace "octoprint/octoprint" with "octoprint:pi"

**Comment by gaetancollaud** [comment]
Pull requests are welcome. I'm using a x86 architecture to run it so I cannot really test it.

**Comment by LongLiveCHIEF** [comment]
Now that we have multi-arch image builds in place, this is the next thing I'm implementing. Currently we're building for `amd64` and `arm64`, but I plan to immediately implement support for any architectures that the ffmpeg static binaries can be installed on, including `armhf` and `armel`

Look for this in the next day or two.
